# Generated by Django 5.2.1 on 2025-05-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='complaintupdate',
            name='author',
        ),
    ]
